### ISSUE TITLE
Broken Drive Link in README

### ISSUE THREAD

**Issue by samwang910325** [hosytuyen/TL-DMI#1]
Thank you for sharing the code; it's greatly appreciated.

I noticed that the link for "both the Pretrained General GAN and the Inversion-Specific GAN"  mentioned in the README file seems to be broken and currently inaccessible.

Would you kindly update the links or provide an alternative way to access these files? 

Thank you again for your time and support.

**Comment by hosytuyen** [comment]
Thank you for your interest.

Apologise for the confusion. We are no longer store our checkpoints in the google drive link.
Instead, we provide the checkpoints in the release tag of this repo (you might find information in Sec. 2 of the README).

Thank you.
